version: '2'
services:
  ingest:
    build: docker/ingest
    hostname: ingest
    links:
      - zookeeper
      - kafka
  
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
   
  kafka:
    image: wurstmeister/kafka:0.10.0.0
    ports:
      - "9092:9092"
    environment:
     KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100 
     KAFKA_PORT: 9092
     KAFKA_ADVERTISED_PORT: 9092
     KAFKA_CREATE_TOPICS: "tweets:1:1,aggregates.v1:1:1" 
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  
